services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: audio-brief-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: yevheniia
      RABBITMQ_DEFAULT_PASS: web_2026
    ports:
      - "5672:5672"
      - "15672:15672"

  minio:
    image: minio/minio:latest
    container_name: audio-brief-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: yevheniia
      MINIO_ROOT_PASSWORD: web_2026
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data: {}
